# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/geotyper/my_projects/CPP/color_move_art2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/geotyper/my_projects/CPP/color_move_art2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geotyper/my_projects/CPP/color_move_art2/CMakeFiles /home/geotyper/my_projects/CPP/color_move_art2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geotyper/my_projects/CPP/color_move_art2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ColorMoveArt2

# Build rule for target.
ColorMoveArt2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ColorMoveArt2
.PHONY : ColorMoveArt2

# fast build rule for target.
ColorMoveArt2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/build
.PHONY : ColorMoveArt2/fast

#=============================================================================
# Target rules for targets named ColorMoveArt2_autogen

# Build rule for target.
ColorMoveArt2_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ColorMoveArt2_autogen
.PHONY : ColorMoveArt2_autogen

# fast build rule for target.
ColorMoveArt2_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2_autogen.dir/build.make CMakeFiles/ColorMoveArt2_autogen.dir/build
.PHONY : ColorMoveArt2_autogen/fast

ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.o: ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.o

ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.i: ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.i

ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.s: ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.cpp.s

ColorMoveArt2_autogen/mocs_compilation.o: ColorMoveArt2_autogen/mocs_compilation.cpp.o
.PHONY : ColorMoveArt2_autogen/mocs_compilation.o

# target to build an object file
ColorMoveArt2_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/ColorMoveArt2_autogen/mocs_compilation.cpp.o
.PHONY : ColorMoveArt2_autogen/mocs_compilation.cpp.o

ColorMoveArt2_autogen/mocs_compilation.i: ColorMoveArt2_autogen/mocs_compilation.cpp.i
.PHONY : ColorMoveArt2_autogen/mocs_compilation.i

# target to preprocess a source file
ColorMoveArt2_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/ColorMoveArt2_autogen/mocs_compilation.cpp.i
.PHONY : ColorMoveArt2_autogen/mocs_compilation.cpp.i

ColorMoveArt2_autogen/mocs_compilation.s: ColorMoveArt2_autogen/mocs_compilation.cpp.s
.PHONY : ColorMoveArt2_autogen/mocs_compilation.s

# target to generate assembly for a file
ColorMoveArt2_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/ColorMoveArt2_autogen/mocs_compilation.cpp.s
.PHONY : ColorMoveArt2_autogen/mocs_compilation.cpp.s

src/AgentProjectionWindow.o: src/AgentProjectionWindow.cpp.o
.PHONY : src/AgentProjectionWindow.o

# target to build an object file
src/AgentProjectionWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/AgentProjectionWindow.cpp.o
.PHONY : src/AgentProjectionWindow.cpp.o

src/AgentProjectionWindow.i: src/AgentProjectionWindow.cpp.i
.PHONY : src/AgentProjectionWindow.i

# target to preprocess a source file
src/AgentProjectionWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/AgentProjectionWindow.cpp.i
.PHONY : src/AgentProjectionWindow.cpp.i

src/AgentProjectionWindow.s: src/AgentProjectionWindow.cpp.s
.PHONY : src/AgentProjectionWindow.s

# target to generate assembly for a file
src/AgentProjectionWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/AgentProjectionWindow.cpp.s
.PHONY : src/AgentProjectionWindow.cpp.s

src/MainWindow.o: src/MainWindow.cpp.o
.PHONY : src/MainWindow.o

# target to build an object file
src/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/MainWindow.cpp.o
.PHONY : src/MainWindow.cpp.o

src/MainWindow.i: src/MainWindow.cpp.i
.PHONY : src/MainWindow.i

# target to preprocess a source file
src/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/MainWindow.cpp.i
.PHONY : src/MainWindow.cpp.i

src/MainWindow.s: src/MainWindow.cpp.s
.PHONY : src/MainWindow.s

# target to generate assembly for a file
src/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/MainWindow.cpp.s
.PHONY : src/MainWindow.cpp.s

src/MeshViewerWidget.o: src/MeshViewerWidget.cpp.o
.PHONY : src/MeshViewerWidget.o

# target to build an object file
src/MeshViewerWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/MeshViewerWidget.cpp.o
.PHONY : src/MeshViewerWidget.cpp.o

src/MeshViewerWidget.i: src/MeshViewerWidget.cpp.i
.PHONY : src/MeshViewerWidget.i

# target to preprocess a source file
src/MeshViewerWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/MeshViewerWidget.cpp.i
.PHONY : src/MeshViewerWidget.cpp.i

src/MeshViewerWidget.s: src/MeshViewerWidget.cpp.s
.PHONY : src/MeshViewerWidget.s

# target to generate assembly for a file
src/MeshViewerWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/MeshViewerWidget.cpp.s
.PHONY : src/MeshViewerWidget.cpp.s

src/SqueegeeWindow.o: src/SqueegeeWindow.cpp.o
.PHONY : src/SqueegeeWindow.o

# target to build an object file
src/SqueegeeWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/SqueegeeWindow.cpp.o
.PHONY : src/SqueegeeWindow.cpp.o

src/SqueegeeWindow.i: src/SqueegeeWindow.cpp.i
.PHONY : src/SqueegeeWindow.i

# target to preprocess a source file
src/SqueegeeWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/SqueegeeWindow.cpp.i
.PHONY : src/SqueegeeWindow.cpp.i

src/SqueegeeWindow.s: src/SqueegeeWindow.cpp.s
.PHONY : src/SqueegeeWindow.s

# target to generate assembly for a file
src/SqueegeeWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/SqueegeeWindow.cpp.s
.PHONY : src/SqueegeeWindow.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ColorMoveArt2.dir/build.make CMakeFiles/ColorMoveArt2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ColorMoveArt2_autogen"
	@echo "... ColorMoveArt2"
	@echo "... ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... ColorMoveArt2_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... ColorMoveArt2_autogen/mocs_compilation.o"
	@echo "... ColorMoveArt2_autogen/mocs_compilation.i"
	@echo "... ColorMoveArt2_autogen/mocs_compilation.s"
	@echo "... src/AgentProjectionWindow.o"
	@echo "... src/AgentProjectionWindow.i"
	@echo "... src/AgentProjectionWindow.s"
	@echo "... src/MainWindow.o"
	@echo "... src/MainWindow.i"
	@echo "... src/MainWindow.s"
	@echo "... src/MeshViewerWidget.o"
	@echo "... src/MeshViewerWidget.i"
	@echo "... src/MeshViewerWidget.s"
	@echo "... src/SqueegeeWindow.o"
	@echo "... src/SqueegeeWindow.i"
	@echo "... src/SqueegeeWindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

